import Foundation

package enum AgentStudioOTLPTraceProjection {
    package static func project(_ record: AgentStudioTraceRecord) -> AgentStudioOTLPProjectedLogRecord {
        let safeResource = safeResource(record.resource)
        let resource = projectedResource(safeResource)
        var attributes = projectedAttributes(record.attributes, resource: safeResource)
        if record.timeUnixNano <= UInt64(Int.max) {
            attributes["agentstudio.event.time_unix_nano"] = .int(Int(record.timeUnixNano))
        }
        return AgentStudioOTLPProjectedLogRecord(
            timeUnixNano: record.timeUnixNano,
            severityText: record.severityText,
            body: safeBody(record.body),
            traceID: validTraceID(record.traceID),
            spanID: validSpanID(record.spanID),
            parentSpanID: validSpanID(record.parentSpanID),
            resource: resource,
            scope: record.scope,
            attributes: attributes
        )
    }
    private static let allowedStringAttributeKeys: Set<String> = Set([
        "agent.proof.marker",
        "agent.proof.launch",
        "agentstudio.app.ipc.start.reason",
        "agentstudio.app.startup.outcome",
        "agentstudio.app.startup.phase",
        "agentstudio.bridge.activation.cause",
        "agentstudio.bridge.activation.from_viewer",
        "agentstudio.bridge.anchor_restore.phase",
        "agentstudio.bridge.cache.result",
        "agentstudio.bridge.comparison.attempt.status",
        "agentstudio.bridge.comparison.package_match",
        "agentstudio.bridge.comparison.pane_state",
        "agentstudio.bridge.content.correlation_mode",
        "agentstudio.bridge.content.interest",
        "agentstudio.bridge.content.priority",
        "agentstudio.bridge.content.role",
        "agentstudio.bridge.content_bytes_bucket",
        "agentstudio.bridge.demand.disposition",
        "agentstudio.bridge.demand.lane",
        "agentstudio.bridge.diff_row_count_bucket",
        "agentstudio.bridge.file_size_bucket",
        "agentstudio.bridge.fixture_class",
        "agentstudio.bridge.frame_jank.kind",
        "agentstudio.bridge.generation.relation",
        "agentstudio.bridge.generation_relation",
        "agentstudio.bridge.input.source",
        "agentstudio.bridge.intake.frame_kind",
        "agentstudio.bridge.item_count_bucket",
        "agentstudio.bridge.item_update.kind",
        "agentstudio.bridge.language_class",
        "agentstudio.bridge.markdown.fallback_reason",
        "agentstudio.bridge.native_capacity.activity_rank",
        "agentstudio.bridge.native_capacity.event",
        "agentstudio.bridge.native_capacity.operation_class",
        "agentstudio.bridge.native_capacity.product_kind",
        "agentstudio.bridge.native_capacity.worktree_hash",
        "agentstudio.bridge.operation.id",
        "agentstudio.bridge.package_build.reason",
        "agentstudio.bridge.panel.operation",
        "agentstudio.bridge.phase",
        "agentstudio.bridge.plane",
        "agentstudio.bridge.priority",
        "agentstudio.bridge.presentation.disposition",
        "agentstudio.bridge.projection.kind",
        "agentstudio.bridge.protocol",
        "agentstudio.bridge.query_class",
        "agentstudio.bridge.queue.depth_bucket",
        "agentstudio.bridge.result",
        "agentstudio.bridge.result_reason",
        "agentstudio.bridge.review.refresh.install_trigger",
        "agentstudio.bridge.review.refresh.presentation_class",
        "agentstudio.bridge.review.refresh.promotion_reason",
        "agentstudio.bridge.rpc.method_class",
        "agentstudio.bridge.scroll.offset",
        "agentstudio.bridge.scroll.reason",
        "agentstudio.bridge.scroll_target.kind",
        "agentstudio.bridge.selection.origin",
        "agentstudio.bridge.slice",
        "agentstudio.bridge.telemetry.drop_reason",
        "agentstudio.bridge.telemetry.event_name",
        "agentstudio.bridge.telemetry.first_rejected_event",
        "agentstudio.bridge.telemetry.lane",
        "agentstudio.bridge.telemetry.result",
        "agentstudio.bridge.telemetry.session.digest",
        "agentstudio.bridge.test.scenario",
        "agentstudio.bridge.transport",
        "agentstudio.bridge.tree_path_count_bucket",
        "agentstudio.bridge.visible_row_bucket",
        "agentstudio.bridge.viewer",
        "agentstudio.bridge.viewer.ttfi_variant",
        "agentstudio.bridge.worker.action",
        "agentstudio.bridge.worker.command",
        "agentstudio.bridge.worker.file_mode_dispatch",
        "agentstudio.bridge.worker.file_select_dispatch",
        "agentstudio.bridge.worker.lane",
        "agentstudio.bridge.worker.payload_class",
        "agentstudio.bridge.worker.review_select_dispatch",
        "agentstudio.bridge.worker.semantic_class",
        "agentstudio.bridge.worker.session_state",
        "agentstudio.bridge.worker.task_kind",
        "agentstudio.bridge.worker.work_kind",
        "agentstudio.command.name",
        "agentstudio.command.source",
        "agentstudio.performance.commandbar.search.stage",
        "agentstudio.performance.commandbar.search.outcome",
        "agentstudio.envelope.scope",
        "agentstudio.eventbus.consumer",
        "agentstudio.eventbus.name",
        "agentstudio.ghostty.action.name",
        "agentstudio.ghostty.route.reason",
        "agentstudio.ghostty.signal.class",
        "agentstudio.performance.interaction.kind", "agentstudio.performance.focus.responder_change.reason",
        "agentstudio.performance.ipc.agent_authorization.outcome",
        "agentstudio.performance.startup.source",
        "agentstudio.performance.startup.deferral.gate",
        "agentstudio.performance.startup.deferral.outcome",
        "agentstudio.inbox.claim.lane", "agentstudio.inbox.claim.semantic",
        "agentstudio.inbox.decision", "agentstudio.inbox.kind",
        "agentstudio.inbox.reason",
        "agentstudio.pane.kind",
        "agentstudio.preferences.global.status",
        "agentstudio.performance.coordinator.phase",
        "agentstudio.performance.atom.kind",
        "agentstudio.performance.atom.label",
        "agentstudio.performance.atom.operation",
        "agentstudio.performance.atom.outcome",
        "agentstudio.performance.git.backoff.reason",
        "agentstudio.performance.git.status.last_outcome",
        "agentstudio.performance.git.status_scope",
        "agentstudio.performance.git.status_unavailable.reason",
        "agentstudio.performance.management_layer.command",
        "agentstudio.performance.pane_action.name",
        "agentstudio.performance.pane.association_outcome",
        "agentstudio.performance.sidebar.group_mode",
        "agentstudio.performance.sidebar.phase", "agentstudio.performance.repo_explorer.wake_trigger",
        "agentstudio.performance.sidebar.query_state",
        "agentstudio.performance.sidebar.surface",
        "agentstudio.performance.sidebar.trigger",
        "agentstudio.performance.sidebar.toggle.intent",
        "agentstudio.performance.tabbar.context_menu.hit_view_class",
        "agentstudio.performance.tabbar.context_menu.phase",
        "agentstudio.performance.tabbar.terminal.outcome",
        "agentstudio.performance.terminal.accumulator.drain.class",
        "agentstudio.performance.terminal.accumulator.apply.outcome",
        "agentstudio.performance.terminal.publication.kind",
        "agentstudio.performance.terminal.geometry.reason",
        "agentstudio.performance.terminal.surface.source",
        "agentstudio.persistence.backend",
        "agentstudio.persistence.classification",
        "agentstudio.persistence.disposition",
        "agentstudio.persistence.lane",
        "agentstudio.persistence.operation",
        "agentstudio.persistence.outcome",
        "agentstudio.persistence.phase",
        "agentstudio.persistence.recovery.attempt",
        "agentstudio.persistence.recovery.kind",
        "agentstudio.persistence.reason",
        "agentstudio.runtime.action_policy",
        "agentstudio.runtime.event",
        "agentstudio.sqlite.database",
        "agentstudio.startup_diagnostic.action",
        "agentstudio.startup_diagnostic.repo_explorer_key_mutation.phase",
        "agentstudio.startup_diagnostic.bridge.file_view.expected_bootstrap.protocol",
        "agentstudio.startup_diagnostic.bridge.file_view.bootstrap.protocol",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_frame_kind",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_reason",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_receiver_reason",
        "agentstudio.startup_diagnostic.bridge.file_view.tree_extent.kind",
        "agentstudio.startup_diagnostic.bridge.selected_content.state",
        "agentstudio.startup_diagnostic.bridge.selected_change_kind",
        "agentstudio.startup_diagnostic.bridge.selected_content.roles",
        "agentstudio.startup_diagnostic.bridge.modified_click.selected_change_kind",
        "agentstudio.startup_diagnostic.bridge.modified_click.selected_content_state",
        "agentstudio.startup_diagnostic.bridge.modified_click.selected_content.roles",
        "agentstudio.startup_diagnostic.bridge.modified_click.selected_materialized.item_type",
        "agentstudio.startup_diagnostic.bridge.modified_click.set_filter.reason",
        "agentstudio.startup_diagnostic.bridge.modified_click.set_filter.status",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.selected_content_state",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.selected_materialized.item_type",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.dispatch_result",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.selection_command.last_result",
        "agentstudio.startup_diagnostic.bridge.review_intake.last_frame_kind",
        "agentstudio.startup_diagnostic.bridge.file_view.open_file.state",
        "agentstudio.startup_diagnostic.bridge.file_view.source.state",
        "agentstudio.startup_diagnostic.bridge.page_issue.last_class",
        "agentstudio.startup_diagnostic.bridge.page_issue.last_kind",
        "agentstudio.startup_diagnostic.bridge.frame_liveness.raf_alive",
        "agentstudio.startup_diagnostic.bridge.frame_liveness.raf_fired_latency.bucket",
        "agentstudio.startup_diagnostic.bridge.painted_probe.last_reason",
        "agentstudio.startup_diagnostic.bridge.painted_probe.last_schedule_early_return.reason",
        "agentstudio.startup_diagnostic.bridge.review_canvas.branch",
        "agentstudio.startup_diagnostic.bridge.review_shell.selected_content.state",
        "agentstudio.startup_diagnostic.bridge.review_shell.state",
        "agentstudio.startup_diagnostic.bridge.selected_demand.load_failure.kind",
        "agentstudio.startup_diagnostic.bridge.selected_demand.result.reason",
        "agentstudio.startup_diagnostic.bridge.selected_demand.result.status",
        "agentstudio.startup_diagnostic.bridge.diff_container.display",
        "agentstudio.startup_diagnostic.bridge.code_view.rendered_item.element.first_child.tag",
        "agentstudio.startup_diagnostic.bridge.code_view.rendered_item.type",
        "agentstudio.startup_diagnostic.bridge.code_view_scroll_owner.first_child.tag",
        "agentstudio.startup_diagnostic.bridge.selected_materialized.item_type",
        "agentstudio.startup_diagnostic.bridge.selected_materialized.update_result",
        "agentstudio.startup_diagnostic.bridge.worker_pool.init_probe.failure_reason",
        "agentstudio.startup_diagnostic.bridge.worker_pool.init_probe.stage",
        "agentstudio.startup_diagnostic.bridge.worker_pool.manager_state",
        "agentstudio.startup_diagnostic.bridge.worker_pool.state",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.bootstrap_state",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.initialize_request_id_state",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_failure_kind",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_forward_result",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_message_type",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_request_type",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_success_id_prefix",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_success_id_state",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_success_matches_initialize_request",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.last_success_request_type",
        "agentstudio.startup_diagnostic.skip_reason",
        "agentstudio.terminal.startup.outcome",
        "agentstudio.terminal.startup.failure.kind",
        "agentstudio.terminal.startup.phase",
        "agentstudio.tcc.access.result",
        "agentstudio.tcc.access.target",
        "agentstudio.tcc.bundle.kind",
        "agentstudio.tcc.code_identity.kind",
        "agentstudio.tcc.command.exit_class",
        "agentstudio.tcc.phase",
        "agentstudio.tcc.responsible.kind",
        "agentstudio.tcc.subject",
        "agentstudio.trace.tag",
        "agentstudio.workspace.boot.step",
        "dev.runtime.flavor",
        "dev.branch.name",
        "terminal.activity.close_reason",
        "terminal.activity.source",
    ]).union(AgentStudioOTLPAttributionProjectionKeys.stringAttributeKeys)
        .union(AgentStudioOTLPRepoExplorerTaxonomy.stringAttributeKeys)
        .union(AgentStudioOTLPPaneDropTaxonomy.stringAttributeKeys)
        .union(BridgeProductStreamProjectionKeys.stringKeys).union(BridgeProductPaintProjectionKeys.stringKeys)
        .union(RendererLifecycleOTLPProjectionKeys.stringAttributeKeys)
    private static let allowedNumericAttributeKeys: Set<String> = Set([
        "agentstudio.sqlite.result_code",
        "agentstudio.bridge.activation.sequence",
        "agentstudio.bridge.active_viewer.sequence",
        "agentstudio.bridge.active_viewer.signal_accepted.count",
        "agentstudio.bridge.annotation.catalog.entry.count",
        "agentstudio.bridge.annotation.catalog.revision",
        "agentstudio.bridge.annotation.catalog.unit.byte_count",
        "agentstudio.bridge.annotation.catalog.window.count",
        "agentstudio.bridge.annotation.catalog.window.ordinal",
        "agentstudio.bridge.batch.sample_count",
        "agentstudio.bridge.content.byte_count",
        "agentstudio.bridge.content.byte_length",
        "agentstudio.bridge.content.byte_size_bucket",
        "agentstudio.bridge.content.body_registry_commit_ms",
        "agentstudio.bridge.content.chunk_byte_count",
        "agentstudio.bridge.content.chunk_count",
        "agentstudio.bridge.content.estimated_bytes",
        "agentstudio.bridge.content.first_chunk_wait_ms",
        "agentstudio.bridge.content.line_count_bucket",
        "agentstudio.bridge.content.response_wait_ms",
        "agentstudio.bridge.content.resource_count",
        "agentstudio.bridge.content.stream_read_ms",
        "agentstudio.bridge.content.total_bytes_read",
        "agentstudio.bridge.frame_jank.dropped_frame.count",
        "agentstudio.bridge.frame_jank.dropped_frame.worst_gap_ms",
        "agentstudio.bridge.frame_jank.long_task.count",
        "agentstudio.bridge.frame_jank.long_task.max_ms",
        "agentstudio.bridge.frame_jank.long_task.total_ms",
        "agentstudio.bridge.demand.active.count",
        "agentstudio.bridge.demand.deferred.count",
        "agentstudio.bridge.demand.duration_ms",
        "agentstudio.bridge.demand.enqueue_accepted.count",
        "agentstudio.bridge.demand.enqueue_rejected.count",
        "agentstudio.bridge.demand.executor_in_flight_ms",
        "agentstudio.bridge.demand.executor_pending_wait_ms",
        "agentstudio.bridge.demand.failed.count",
        "agentstudio.bridge.demand.foreground.count",
        "agentstudio.bridge.demand.idle.count",
        "agentstudio.bridge.demand.intent.count",
        "agentstudio.bridge.demand.loaded.count",
        "agentstudio.bridge.demand.nearby.count",
        "agentstudio.bridge.demand.request.sequence",
        "agentstudio.bridge.demand.overflow_drop.count",
        "agentstudio.bridge.demand.job_execution_ms",
        "agentstudio.bridge.demand.queue_depth",
        "agentstudio.bridge.demand.scheduler_queue_wait_ms",
        "agentstudio.bridge.demand.speculative.count",
        "agentstudio.bridge.demand.stale_drop.count",
        "agentstudio.bridge.demand.visible.count",
        "agentstudio.bridge.intake.generation",
        "agentstudio.bridge.intake.sequence",
        "agentstudio.bridge.markdown.input_bytes",
        "agentstudio.bridge.markdown.output_bytes",
        "agentstudio.bridge.native_capacity.coalesced_waiter.count",
        "agentstudio.bridge.native_capacity.deadline.count",
        "agentstudio.bridge.native_capacity.draining.count",
        "agentstudio.bridge.native_capacity.entry.count",
        "agentstudio.bridge.native_capacity.fairness_history.count",
        "agentstudio.bridge.native_capacity.in_flight.count",
        "agentstudio.bridge.native_capacity.lease.count",
        "agentstudio.bridge.native_capacity.locator.count",
        "agentstudio.bridge.native_capacity.logical_waiter.count",
        "agentstudio.bridge.native_capacity.occupied_slot.count",
        "agentstudio.bridge.native_capacity.pane_activity.count",
        "agentstudio.bridge.native_capacity.payload.count",
        "agentstudio.bridge.native_capacity.queued.count",
        "agentstudio.bridge.native_capacity.retained_artifact_byte.count",
        "agentstudio.bridge.native_capacity.running.count",
        "agentstudio.bridge.native_capacity.tombstone.count",
        "agentstudio.bridge.native_capacity.waiter.count",
        "agentstudio.bridge.native_capacity.worktree.count",
        "agentstudio.bridge.metadata_manifest.emitted_total",
        "agentstudio.bridge.metadata_manifest.expected_total",
        "agentstudio.bridge.metadata_manifest.remaining_total",
        "agentstudio.bridge.presentation.publication_sequence",
        "agentstudio.bridge.presentation.revision",
        "agentstudio.bridge.presentation.revision.after",
        "agentstudio.bridge.presentation.revision.before",
        "agentstudio.bridge.review.item_count",
        "agentstudio.bridge.review.generation",
        "agentstudio.bridge.review.refresh.active_bank.count",
        "agentstudio.bridge.review.refresh.affected_file.count",
        "agentstudio.bridge.review.refresh.affected_stable_file.count",
        "agentstudio.bridge.review.refresh.candidate_bank.count",
        "agentstudio.bridge.review.refresh.changed_line.count",
        "agentstudio.bridge.review.refresh.imported_commit.count",
        "agentstudio.bridge.review.refresh.retained_publication.count",
        "agentstudio.bridge.review.refresh.source_lease.count",
        "agentstudio.bridge.review.publication.emitted_events",
        "agentstudio.bridge.review.publication.published_subscriptions",
        "agentstudio.bridge.review.publication.retained",
        "agentstudio.bridge.review.publication.superseded",
        "agentstudio.bridge.source.generation",
        "agentstudio.bridge.stage.attempt",
        "agentstudio.bridge.anchor_restore.call.count",
        "agentstudio.bridge.anchor_restore.direct_scroll_top_write.count",
        "agentstudio.bridge.anchor_restore.synthetic_scroll.count",
        "agentstudio.bridge.scroll.frame_gap.max_ms",
        "agentstudio.bridge.scroll.frame_gap.over_16ms.count",
        "agentstudio.bridge.scroll.frame_gap.over_33ms.count",
        "agentstudio.bridge.scroll.frame_gap.over_50ms.count",
        "agentstudio.bridge.scroll.frame_gap.p95_ms",
        "agentstudio.bridge.selected_content.click_to_paint_ms",
        "agentstudio.bridge.selected_content.frame_wait_ms",
        "agentstudio.bridge.selected_content.materialize_ms",
        "agentstudio.bridge.telemetry.dropped_count",
        "agentstudio.bridge.telemetry.accepted_batch.sequence",
        "agentstudio.bridge.telemetry.comm_producer.high_watermark",
        "agentstudio.bridge.telemetry.main_producer.high_watermark",
        "agentstudio.bridge.telemetry.native_batch_sequence_gap.count",
        "agentstudio.bridge.telemetry.optional_loss.count",
        "agentstudio.bridge.telemetry.required_dropped_count",
        "agentstudio.bridge.telemetry.required_loss.count",
        "agentstudio.bridge.telemetry.worker_sequence_gap.count",
        "agentstudio.bridge.visible_descriptor.count",
        "agentstudio.bridge.visible_item.count",
        "agentstudio.bridge.visible_publisher.skipped.count",
        "agentstudio.bridge.visible_row.count",
        "agentstudio.bridge.worktree_file.pending_frame.count",
        "agentstudio.bridge.worktree_file.tree.all_row.count",
        "agentstudio.bridge.worktree_file.tree.current_row.count",
        "agentstudio.bridge.worktree_file.tree.descriptor.count",
        "agentstudio.bridge.worktree_file.tree.discovered_row.count",
        "agentstudio.bridge.worktree_file.tree.first_sequence",
        "agentstudio.bridge.worktree_file.tree.incoming_frame.count",
        "agentstudio.bridge.worktree_file.tree.initial_row.count",
        "agentstudio.bridge.worktree_file.tree.window.dispatch_elapsed_ms",
        "agentstudio.bridge.worktree_file.tree.window.prepare_elapsed_ms",
        "agentstudio.bridge.worktree_file.tree.window.row.count",
        "agentstudio.bridge.worktree_file.tree.window.sequence",
        "agentstudio.bridge.worktree_file.tree.window.start_index",
        "agentstudio.bridge.worktree_file.tree.window.count",
        "agentstudio.bridge.worker.handler_duration_ms",
        "agentstudio.bridge.worker.native_bootstrap_install.count",
        "agentstudio.bridge.worker.derivation_epoch",
        "agentstudio.bridge.worker.patch_count",
        "agentstudio.bridge.worker.queued_command.count",
        "agentstudio.bridge.worker.queue_wait_ms",
        "agentstudio.bridge.worker.replacement_request.count",
        "agentstudio.bridge.worker.source_epoch",
        "agentstudio.bridge.worker.touched_key_count",
        "agentstudio.display.count",
        "agentstudio.envelope.schema_version",
        "agentstudio.envelope.seq",
        "agentstudio.ghostty.action.tag",
        "agentstudio.ghostty.status",
        "agentstudio.inbox.global_unread_after",
        "agentstudio.inbox.global_unread_before",
        "agentstudio.inbox.global_unread_count",
        "agentstudio.pane_inbox.cleared_count",
        "agentstudio.pane_inbox.keep_count",
        "agentstudio.preferences.global.load_elapsed_ms",
        "agentstudio.preferences.global.schema_version",
        "agentstudio.performance.atom.accepted_change.count",
        "agentstudio.performance.atom.cached_key.count",
        "agentstudio.performance.atom.input_revision.count",
        "agentstudio.performance.atom.slot.count",
        "agentstudio.performance.commandbar.input.count",
        "agentstudio.performance.commandbar.input_worktree_row.count",
        "agentstudio.performance.apply_governor.batch.count",
        "agentstudio.performance.apply_governor.carried_over.count",
        "agentstudio.performance.apply_governor.superseded.count",
        "agentstudio.performance.commandbar.item.count",
        "agentstudio.performance.commandbar.worktree_row.count",
        "agentstudio.performance.commandbar.pane.count",
        "agentstudio.performance.commandbar.query_character.count",
        "agentstudio.performance.commandbar.repo.count",
        "agentstudio.performance.commandbar.result.count",
        "agentstudio.performance.commandbar.search.sequence",
        "agentstudio.performance.commandbar.search.generation",
        "agentstudio.performance.commandbar.search.duplicate_item.count",
        "agentstudio.performance.commandbar.result_worktree_row.count",
        "agentstudio.performance.commandbar.worktree.count",
        "agentstudio.performance.elapsed_ms",
        "agentstudio.performance.repository_lifecycle.repository.count",
        "agentstudio.performance.repository_lifecycle.observation.count",
        "agentstudio.performance.repository_lifecycle.changed_family.count",
        "agentstudio.performance.repository_lifecycle.collected_location.count",
        "agentstudio.performance.repository_lifecycle.mainactor_held_ms",
        "agentstudio.performance.startup.layout_settle_to_usable_elapsed_ms",
        "agentstudio.performance.filesystem.drain_task.count",
        "agentstudio.performance.filesystem.affected_key_request.count",
        "agentstudio.performance.filesystem.full_reconciliation_request.count",
        "agentstudio.performance.filesystem.logical_debt.count",
        "agentstudio.performance.filesystem.pending_worktree.count",
        "agentstudio.performance.filesystem.watched_folder.active.count",
        "agentstudio.performance.filesystem.watched_folder.dirty_follow_up.count",
        "agentstudio.performance.filesystem.watched_folder.ready.count",
        "agentstudio.performance.git.admitted.count",
        "agentstudio.performance.git.available_slot.count",
        "agentstudio.performance.git.backoff_attempt.count",
        "agentstudio.performance.git.backoff_ms",
        "agentstudio.performance.git.dropped_subscriber.count",
        "agentstudio.performance.git.enqueued.count",
        "agentstudio.performance.git.event_posted.count",
        "agentstudio.performance.git.input_path.count",
        "agentstudio.performance.git.pathspec.count",
        "agentstudio.performance.git.logical_debt.count",
        "agentstudio.performance.git.logical_pending.count",
        "agentstudio.performance.git.logical_running.count",
        "agentstudio.performance.git.future_automatic.count",
        "agentstudio.performance.git.future_failure.count",
        "agentstudio.performance.git.ready_pending.count",
        "agentstudio.performance.git.capacity_pending.count",
        "agentstudio.performance.git.active_follow_up.count",
        "agentstudio.performance.git.unclassified_pending.count",
        "agentstudio.performance.git.overdue_deadline.count",
        "agentstudio.performance.git.oldest_preparation_ms",
        "agentstudio.performance.git.next_deadline_ms",
        "agentstudio.performance.git.background_only_automatic.current",
        "agentstudio.performance.git.background_only_automatic_deadline.current",
        "agentstudio.performance.git.background_only_resolved_visible_tier.current",
        "agentstudio.performance.git.pending.count",
        "agentstudio.performance.git.registered.count",
        "agentstudio.performance.git.request.sequence",
        "agentstudio.performance.git.retry_pending.count",
        "agentstudio.performance.git.running.count",
        "agentstudio.performance.git.snapshot_dedup.count",
        "agentstudio.performance.git.status.consecutive_failure.count",
        "agentstudio.performance.git.status.duration_ms",
        "agentstudio.performance.git.status.elapsed_ms",
        "agentstudio.performance.git.suppressed_git_internal_path.count",
        "agentstudio.performance.git.suppressed_ignored_path.count",
        "agentstudio.performance.git.tick.count",
        "agentstudio.performance.process.malloc.blocks_in_use",
        "agentstudio.performance.process.malloc.maximum_size_in_use_bytes",
        "agentstudio.performance.process.malloc.size_allocated_bytes",
        "agentstudio.performance.process.malloc.size_in_use_bytes",
        "agentstudio.performance.runtime_delivery.eventbus_active_delivery_debt.count",
        "agentstudio.performance.runtime_delivery.eventbus_active_subscriber.count",
        "agentstudio.performance.runtime_delivery.eventbus_live_dropped.count",
        "agentstudio.performance.runtime_delivery.eventbus_replay_dropped.count",
        "agentstudio.performance.runtime_delivery.eventbus_retired_undelivered.count",
        "agentstudio.performance.runtime_delivery.runtime_channel_outbound_dropped.count",
        "agentstudio.performance.runtime_delivery.runtime_channel_outbound_pending.count",
        "agentstudio.performance.runtime_delivery.runtime_channel_retired_undelivered.count",
        "agentstudio.performance.runtime_delivery.total_pending.count",
        "agentstudio.ghostty.surface.environment_variable_count",
        "agentstudio.ghostty.surface.initial_frame_height",
        "agentstudio.ghostty.surface.initial_frame_width",
        "agentstudio.performance.management_layer.pane.count",
        "agentstudio.performance.management_layer.tab.count",
        "agentstudio.performance.pane_action.pane.count",
        "agentstudio.performance.pane_action.tab.count",
        "agentstudio.performance.pane.association_boot.pane.count",
        "agentstudio.performance.pane.association_boot.retained_known.count",
        "agentstudio.performance.pane.association_boot.backfilled.count",
        "agentstudio.performance.pane.association_boot.dangling_cleared.count",
        "agentstudio.performance.pane.association_boot.free_nil.count",
        "agentstudio.performance.pane.association_boot.changed.count",
        "agentstudio.performance.pane_tab_layout.pane.count",
        "agentstudio.performance.pane_tab_layout.subview.count",
        "agentstudio.performance.pane_tab_layout.tab.count",
        "agentstudio.performance.pane_view_restore.pane.count",
        "agentstudio.performance.pane_view_restore.tab.count",
        "agentstudio.performance.pane_view_restore.visible_pane.count",
        "agentstudio.performance.repo_explorer.command_resolution.count",
        "agentstudio.performance.repo_explorer.command_reused.count",
        "agentstudio.performance.repo_explorer.outline_apply_proxy.equal_publish.count",
        "agentstudio.performance.repo_explorer.outline_apply_proxy.rows_changed.count",
        "agentstudio.performance.repo_explorer.outline_apply_proxy.rows_total.count",
        "agentstudio.performance.repo_explorer.outline_apply_proxy.mainactor_held_ms",
        "agentstudio.performance.repo_explorer.frame_sample.sequence",
        "agentstudio.performance.repo_explorer.interval.count",
        "agentstudio.performance.repo_explorer.scroll_burst.sequence",
        "agentstudio.performance.repo_explorer.visible_set.count",
        "agentstudio.performance.repo_explorer.visible_set_delta.count",
        "agentstudio.performance.sidebar.collapsed_group.count",
        "agentstudio.performance.sidebar.group.count", "agentstudio.performance.sidebar.input.count",
        "agentstudio.performance.sidebar.loading_repo.count",
        "agentstudio.performance.sidebar.mainactor_apply_elapsed_ms",
        "agentstudio.performance.sidebar.query_character.count",
        "agentstudio.performance.sidebar.repo.count",
        "agentstudio.performance.sidebar.request_build_mainactor_elapsed_ms",
        "agentstudio.performance.sidebar.row_index_elapsed_ms",
        "agentstudio.performance.sidebar.stale_discard.count",
        "agentstudio.performance.sidebar.cancellation.count",
        "agentstudio.performance.sidebar.total_worker_elapsed_ms",
        "agentstudio.performance.sidebar.split_width",
        "agentstudio.performance.sidebar.width",
        "agentstudio.performance.tabbar.pane.count",
        "agentstudio.performance.tabbar.affected_item.count",
        "agentstudio.performance.tabbar.mainactor_held_ms",
        "agentstudio.performance.tabbar.queue_wait_ms",
        "agentstudio.performance.tabbar.sequence",
        "agentstudio.performance.tabbar.source_tab.count",
        "agentstudio.performance.tabbar.tab.count",
        "agentstudio.performance.trace_queue.dropped_record.count",
        "agentstudio.performance.trace_queue.high_watermark",
        "agentstudio.performance.trace_queue.pending_request.count",
        "agentstudio.performance.terminal.accumulator.equal_suppressed.count",
        "agentstudio.performance.terminal.accumulator.follow_up_drain.count",
        "agentstudio.performance.terminal.accumulator.mainactor_task.count",
        "agentstudio.performance.terminal.accumulator.offered.count",
        "agentstudio.performance.terminal.accumulator.replaced.count",
        "agentstudio.performance.terminal.accumulator.retained_entry.count",
        "agentstudio.performance.terminal.accumulator.retained_size_bytes",
        "agentstudio.performance.terminal.accumulator.scheduled_drain.count",
        "agentstudio.performance.terminal.activity_aggregate.count",
        "agentstudio.performance.terminal.activity_projection.round_trip_ms",
        "agentstudio.performance.terminal.activity_projection.close_read_ms",
        "agentstudio.performance.terminal.equal_write_suppressed.count",
        "agentstudio.performance.terminal.equal_suppressed.count",
        "agentstudio.performance.terminal.geometry.visible_terminal.count",
        "agentstudio.performance.terminal.surface.cell_height_px",
        "agentstudio.performance.terminal.surface.cell_width_px",
        "agentstudio.performance.terminal.surface.column.count",
        "agentstudio.performance.terminal.surface.current_height_px",
        "agentstudio.performance.terminal.surface.current_width_px",
        "agentstudio.performance.terminal.surface.requested_height_px",
        "agentstudio.performance.terminal.surface.requested_width_px",
        "agentstudio.performance.terminal.surface.row.count",
        "agentstudio.performance.topology.index.count",
        "agentstudio.performance.trace_identity.coalesced_request.count",
        "agentstudio.performance.trace_identity.equal_snapshot_suppressed.count",
        "agentstudio.performance.trace_identity.fleet_capture.count",
        "agentstudio.performance.trace_identity.refresh_request.count",
        "agentstudio.startup_diagnostic.created_pane.count",
        "agentstudio.startup_diagnostic.expected_visible_pane.count",
        "agentstudio.startup_diagnostic.bridge.code_line.count",
        "agentstudio.startup_diagnostic.bridge.code_line_with_data_line.count",
        "agentstudio.startup_diagnostic.bridge.code_shadow_text.length",
        "agentstudio.startup_diagnostic.bridge.code_text.length",
        "agentstudio.startup_diagnostic.bridge.bridge_command.count",
        "agentstudio.startup_diagnostic.bridge.bridge_response.count",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.first_item.height_px",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.first_item.top_px",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.height_px",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.item.count",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.render_state.first_index",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.render_state.last_index",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.scroll_height_px",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.window.bottom_px",
        "agentstudio.startup_diagnostic.bridge.code_view.instance.window.top_px",
        "agentstudio.startup_diagnostic.bridge.code_view.rendered_item.count",
        "agentstudio.startup_diagnostic.bridge.code_view.rendered_item.element.child.count",
        "agentstudio.startup_diagnostic.bridge.code_view.rendered_item.element.height_px",
        "agentstudio.startup_diagnostic.bridge.code_view.rendered_item.version",
        "agentstudio.startup_diagnostic.bridge.code_view_scroll_owner.child.count",
        "agentstudio.startup_diagnostic.bridge.code_view_scroll_owner.height_px",
        "agentstudio.startup_diagnostic.bridge.code_view_scroll_owner.scroll_height_px",
        "agentstudio.startup_diagnostic.bridge.code_view_panel.height_px",
        "agentstudio.startup_diagnostic.bridge.code_view_panel.width_px",
        "agentstudio.startup_diagnostic.bridge.diff_container.count",
        "agentstudio.startup_diagnostic.bridge.diff_container.height_px",
        "agentstudio.startup_diagnostic.bridge.diff_container.offset_height_px",
        "agentstudio.startup_diagnostic.bridge.diff_container.pre.count",
        "agentstudio.startup_diagnostic.bridge.diff_container.pre.height_px",
        "agentstudio.startup_diagnostic.bridge.diff_container.pre_text.length",
        "agentstudio.startup_diagnostic.bridge.diff_container.scroll_height_px",
        "agentstudio.startup_diagnostic.bridge.diff_container.shadow_child.count",
        "agentstudio.startup_diagnostic.bridge.diff_container.width_px",
        "agentstudio.startup_diagnostic.bridge.file_view.body_preview.length",
        "agentstudio.startup_diagnostic.bridge.file_view.bridge_command.count",
        "agentstudio.startup_diagnostic.bridge.file_view.bridge_response.count",
        "agentstudio.startup_diagnostic.bridge.file_view.click.body_preview.length",
        "agentstudio.startup_diagnostic.bridge.file_view.second_click.body_preview.length",
        "agentstudio.startup_diagnostic.bridge.file_view.offscreen_click.body_preview.length",
        "agentstudio.startup_diagnostic.bridge.file_view.code_text.length",
        "agentstudio.startup_diagnostic.bridge.file_view.code_view.height_px",
        "agentstudio.startup_diagnostic.bridge.file_view.code_view.width_px",
        "agentstudio.startup_diagnostic.bridge.file_view.descriptor.count",
        "agentstudio.startup_diagnostic.bridge.file_view.descriptor_request_command.count",
        "agentstudio.startup_diagnostic.bridge.file_view.intake_frame.count",
        "agentstudio.startup_diagnostic.bridge.file_view.intake_ready_command.count",
        "agentstudio.startup_diagnostic.bridge.file_view.metadata_file_row.count",
        "agentstudio.startup_diagnostic.bridge.file_view.metadata_tree_row.count",
        "agentstudio.startup_diagnostic.bridge.file_view.mode_switch.count",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.count",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.failure_drop.count",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.frame_evidence.count",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.final_generation",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.final_generation_frame_evidence.count",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_generation",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_receiver_generation",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_sequence",
        "agentstudio.startup_diagnostic.bridge.file_view.open_source_command.count",
        "agentstudio.startup_diagnostic.bridge.file_view.tree_path.count",
        "agentstudio.startup_diagnostic.bridge.file_view.tree_scroll_stress.count",
        "agentstudio.startup_diagnostic.bridge.file_view.total_descriptor.count",
        "agentstudio.startup_diagnostic.bridge.file_view.tree.height_px",
        "agentstudio.startup_diagnostic.bridge.page_issue.count",
        "agentstudio.startup_diagnostic.bridge.page_issue.disallowed.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.already_painted_by_hydration.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.anchored_delivery_anchor_present.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.anchored_delivery_entry.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.anchored_delivery_recorder_present.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.anchored_delivery_selected_match.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.early_return.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.flush_called.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.generation_superseded.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.raf_fired.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.raf_scheduled.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.sample_recorded.count",
        "agentstudio.startup_diagnostic.bridge.painted_probe.schedule_entered.count",
        "agentstudio.startup_diagnostic.bridge.review_expected_item.count",
        "agentstudio.startup_diagnostic.bridge.intake_frame.count",
        "agentstudio.startup_diagnostic.bridge.review_intake_metadata_window_frame.count",
        "agentstudio.startup_diagnostic.bridge.review_intake_ready_command.count",
        "agentstudio.startup_diagnostic.bridge.review_intake_snapshot_frame.count",
        "agentstudio.startup_diagnostic.bridge.review_metadata_item.count",
        "agentstudio.startup_diagnostic.bridge.review_metadata_tree_row.count",
        "agentstudio.startup_diagnostic.bridge.review_tree.client_height_px",
        "agentstudio.startup_diagnostic.bridge.review_tree.scroll_height_px",
        "agentstudio.startup_diagnostic.bridge.review_tree_scroll_stress.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.click_attempt.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.rendered_row.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.rendered_row_count_at_dispatch",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.rendered_row_count_at_find",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.rendered_row_count_delta_before_dispatch",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.selection_poll.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.selection_poll.last_index",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.handler_invoked_delta",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.selection_command_issued_delta",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.selection_command_accepted.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.polls_to_selection_match",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.probe.click_to_selection_ms",
        "agentstudio.startup_diagnostic.bridge.modified_click.click_attempt.count",
        "agentstudio.startup_diagnostic.bridge.modified_click.rendered_row.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.selected_content_character.count",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.selected_materialized.item_version",
        "agentstudio.startup_diagnostic.bridge.review_tree_click.target_row.index",
        "agentstudio.startup_diagnostic.bridge.modified_click.selected_content_character.count",
        "agentstudio.startup_diagnostic.bridge.modified_click.selected_materialized.item_version",
        "agentstudio.startup_diagnostic.bridge.worker_pool.active_tasks",
        "agentstudio.startup_diagnostic.bridge.worker_pool.busy_workers",
        "agentstudio.startup_diagnostic.bridge.worker_pool.diff_cache_size",
        "agentstudio.startup_diagnostic.bridge.worker_pool.file_cache_size",
        "agentstudio.startup_diagnostic.bridge.worker_pool.init_probe.language_count",
        "agentstudio.startup_diagnostic.bridge.worker_pool.init_probe.theme_count",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.diff_success_count",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.failure_count",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.file_success_count",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.forwarded_message_count",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.initialize_success_count",
        "agentstudio.startup_diagnostic.bridge.worker_diagnostic.success_count",
        "agentstudio.startup_diagnostic.bridge.worker_pool.queued_tasks",
        "agentstudio.startup_diagnostic.bridge.worker_pool.total_workers",
        "agentstudio.startup_diagnostic.bridge.selected_content_cache_key.count",
        "agentstudio.startup_diagnostic.bridge.selected_content_character.count",
        "agentstudio.startup_diagnostic.bridge.selected_content_line.count",
        "agentstudio.startup_diagnostic.bridge.selected_content_role.count",
        "agentstudio.startup_diagnostic.bridge.selected_demand.deferred.count",
        "agentstudio.startup_diagnostic.bridge.selected_demand.failed.count",
        "agentstudio.startup_diagnostic.bridge.selected_demand.loaded.count",
        "agentstudio.startup_diagnostic.bridge.selected_materialized.addition_line.count",
        "agentstudio.startup_diagnostic.bridge.selected_materialized.deletion_line.count",
        "agentstudio.startup_diagnostic.bridge.selected_materialized.file_line.count",
        "agentstudio.startup_diagnostic.bridge.selected_materialized.item_version",
        "agentstudio.startup_diagnostic.fixture.surface.count",
        "agentstudio.startup_diagnostic.fixture.surface_reference.count",
        "agentstudio.startup_diagnostic.fixture.terminal_view.count",
        "agentstudio.startup_diagnostic.fixture.valid_geometry.count",
        "agentstudio.startup_diagnostic.fixture.inbox_notification.count",
        "agentstudio.startup_diagnostic.fixture.active_pty.count",
        "agentstudio.startup_diagnostic.fixture.pane.count",
        "agentstudio.startup_diagnostic.fixture.repo.count",
        "agentstudio.startup_diagnostic.fixture.sidebar_surface.count",
        "agentstudio.startup_diagnostic.fixture.tab.count",
        "agentstudio.startup_diagnostic.fixture.worktree.count",
        "agentstudio.startup_diagnostic.repo_explorer_key_mutation.count",
        "agentstudio.terminal.startup.failure.creation_retry.count",
        "agentstudio.tcc.probe.sequence",
        "agentstudio.tcc.tccdb.path_row.count",
        "agentstudio.workspace.snapshot.pane_count",
        "agentstudio.zmx.socket_path_headroom",
        "terminal.activity.baseline_rows",
        "terminal.activity.debounce_ms",
        "terminal.activity.duration_ms",
        "terminal.activity.event_count",
        "terminal.activity.latest_rows",
        "terminal.activity.rows_added",
        "terminal.activity.threshold_rows",
    ]).union(AgentStudioCoordinationProjectionKeys.numericKeys)
        .union(AgentStudioOTLPPaneDropTaxonomy.numericAttributeKeys)
        .union(AgentStudioOTLPRepoExplorerTaxonomy.numericAttributeKeys)
        .union(BridgeProductStreamProjectionKeys.numericKeys).union(BridgeProductPaintProjectionKeys.numericKeys)
        .union(BridgeComparisonTargetCatalogTelemetryKeys.numericAttributeKeys)
        .union(RendererLifecycleOTLPProjectionKeys.numericAttributeKeys)
}
extension AgentStudioOTLPTraceProjection {
    private static func projectedAttributes(
        _ attributes: [String: AgentStudioTraceValue],
        resource: [String: String]
    ) -> [String: AgentStudioTraceValue] {
        var projected: [String: AgentStudioTraceValue] = [:]
        for (key, value) in attributes {
            guard let value = projectedAttributeValue(key: key, value: value) else {
                continue
            }
            projected[key] = value
        }
        for (key, value) in resource where resourceKeysProjectedAsLogAttributes.contains(key) {
            projected[key] = .string(value)
        }
        return projected
    }
}
extension AgentStudioOTLPTraceProjection {
    private static let allowedResourceKeys: Set<String> = [
        "agentstudio.build.config",
        "agentstudio.release_channel",
        "agentstudio.runtime_flavor",
        "agent.proof.launch",
        "agent.proof.marker",
        "dev.build.config",
        "dev.branch.name",
        "dev.release.channel",
        "dev.repo.hash",
        "dev.runtime.flavor",
        "dev.worktree.hash",
        "service.name",
        "service.version",
    ]
    private static let allowedSafeResourceKeys: Set<String> = allowedResourceKeys

    private static let allowedPayloadNamedStringAttributeKeys: Set<String> = [
        "agentstudio.bridge.tree_path_count_bucket",
        "agentstudio.bridge.worker.payload_class",
        "agentstudio.performance.tabbar.context_menu.hit_view_class",
        "agentstudio.performance.tabbar.context_menu.phase",
    ]

    private static func projectedResource(_ safeResource: [String: String]) -> [String: String] {
        safeResource.filter { key, _ in
            allowedResourceKeys.contains(key)
        }
    }

    private static func projectedAttributeValue(key: String, value: AgentStudioTraceValue)
        -> AgentStudioTraceValue?
    {
        if key == "agentstudio.bridge.operation.id" {
            guard case .string(let operationID) = value,
                operationID.count == 64,
                operationID.allSatisfy({ $0.isHexDigit && !$0.isUppercase })
            else { return nil }
            return .string(operationID)
        }
        guard
            !isIdentifierKey(key)
                || AgentStudioOTLPRepoExplorerTaxonomy.controlledIdentifierAttributeKeys.contains(
                    key
                ),
            !isErrorKey(key)
        else {
            return nil
        }
        switch value {
        case .string(let stringValue):
            guard
                !isPayloadKey(key) || allowedPayloadNamedStringAttributeKeys.contains(key),
                allowedStringAttributeKeys.contains(key),
                isSafeControlledString(key: key, value: stringValue),
                isAllowedControlledStringValue(key: key, value: stringValue)
            else { return nil }
            return .string(stringValue)
        case .int:
            return isAllowedNumericKey(key) ? value : nil
        case .double:
            return isAllowedNumericKey(key) ? value : nil
        case .bool:
            return isAllowedBooleanKey(key) ? value : nil
        case .stringArray:
            return nil
        }
    }
    private static func safeResource(_ resource: [String: String]) -> [String: String] {
        var projected: [String: String] = [:]
        for (key, value) in resource where allowedSafeResourceKeys.contains(key) && isSafeResourceValue(value) {
            projected[key] = value
        }
        return projected
    }
    private static let resourceKeysProjectedAsLogAttributes: Set<String> = [
        "agentstudio.release_channel",
        "agentstudio.runtime_flavor",
        "agent.proof.launch",
        "agent.proof.marker",
        "dev.release.channel",
        "dev.repo.hash",
        "dev.runtime.flavor",
        "dev.worktree.hash",
        "dev.branch.name",
        "service.version",
    ]
    private static func isAllowedNumericKey(_ key: String) -> Bool {
        allowedNumericAttributeKeys.contains(key)
    }
    private static func isAllowedBooleanKey(_ key: String) -> Bool {
        AgentStudioOTLPAllowedBooleanAttributes.keys.contains(key)
    }
    private static func isIdentifierKey(_ key: String) -> Bool {
        let normalizedKey = key.lowercased()
        return normalizedKey.hasSuffix(".id")
            || normalizedKey.contains(".id.")
            || normalizedKey.hasSuffix("_id")
            || normalizedKey.contains("_id.")
    }
    private static func isErrorKey(_ key: String) -> Bool {
        key.lowercased().contains("error")
    }
    private static func isPayloadKey(_ key: String) -> Bool {
        let normalizedKey = key.lowercased()
        return normalizedKey.contains("path")
            || normalizedKey.contains("payload")
            || normalizedKey.contains("prompt")
            || normalizedKey.contains("output")
            || normalizedKey.contains("text")
    }
    private static func safeBody(_ body: String) -> String {
        isSafeEventName(body) ? body : "agentstudio.trace.record"
    }
    private static func isSafeEventName(_ value: String) -> Bool {
        guard !value.isEmpty, value.count <= 128 else {
            return false
        }
        return value.unicodeScalars.allSatisfy { scalar in
            CharacterSet.alphanumerics.contains(scalar)
                || scalar == "."
                || scalar == "_"
                || scalar == "-"
                || scalar == ":"
        }
    }
    private static func isSafeControlledString(key: String, value: String) -> Bool {
        if AgentStudioOTLPRepoExplorerTaxonomy.structuredStringAttributeKeys.contains(key) {
            return AgentStudioOTLPRepoExplorerTaxonomy.isAllowedValue(key: key, value: value) == true
        }
        return isSafeEventName(value)
    }
    private static func isSafeResourceValue(_ value: String) -> Bool {
        guard !value.isEmpty, value.count <= 160 else {
            return false
        }
        let normalizedValue = value.lowercased()
        return !normalizedValue.hasPrefix("/")
            && !normalizedValue.contains("/users/")
            && !normalizedValue.contains("://")
            && !normalizedValue.contains("\\")
            && !normalizedValue.contains("\n")
            && !normalizedValue.contains("\r")
    }
    private static func validTraceID(_ value: String?) -> String? {
        validHexIdentifier(value, requiredLength: 32)
    }
    private static func validSpanID(_ value: String?) -> String? {
        validHexIdentifier(value, requiredLength: 16)
    }
    private static func validHexIdentifier(_ value: String?, requiredLength: Int) -> String? {
        guard let value, value.count == requiredLength else {
            return nil
        }
        guard value.utf8.contains(where: { $0 != 48 }) else {
            return nil
        }
        guard
            value.utf8.allSatisfy({ byte in
                byte >= 48 && byte <= 57 || byte >= 97 && byte <= 102
            })
        else {
            return nil
        }
        return value
    }
}
