import Foundation

enum BridgeComparisonTargetCatalogTelemetryKeys {
    static let numericAttributeKeys: Set<String> = [
        "agentstudio.bridge.review.comparison_targets.input_row.count",
        "agentstudio.bridge.review.comparison_targets.output_row.count",
        "agentstudio.bridge.review.comparison_targets.query_request.sequence",
        "agentstudio.bridge.review.comparison_targets.reservation_age_ms",
    ]

    static let booleanAttributeKeys: Set<String> = ["agentstudio.bridge.review.comparison_targets.is_truncated"]
}

extension BridgeTelemetryWireSchema {
    static let requiredStringAttributeKeys: Set<String> = [
        "agentstudio.bridge.phase",
        "agentstudio.bridge.plane",
        "agentstudio.bridge.priority",
        "agentstudio.bridge.slice",
        "agentstudio.bridge.transport",
    ]

    static let allowedEventNames: Set<String> = Set([
        "performance.bridge.swift.active_viewer_mode_signal_accepted",
        "performance.bridge.swift.active_viewer_mode_signal_rejected",
        "performance.bridge.swift.annotation_lifecycle",
        "performance.bridge.swift.operation_lifecycle",
        "performance.bridge.swift.review_refresh_lifecycle",
        "performance.bridge.swift.active_viewer_mode_suppression_catch_up",
        "performance.bridge.git_read_scheduler",
        "performance.bridge.worktree_product_construction",
        "performance.bridge.web.code_view_item_materialize",
        "performance.bridge.web.annotation_lifecycle",
        "performance.bridge.web.operation_lifecycle",
        "performance.bridge.web.review_refresh_lifecycle",
        "performance.bridge.web.comm_worker_session",
        "performance.bridge.web.content_fetch",
        "performance.bridge.web.first_render",
        "performance.bridge.web.frame_jank",
        "performance.bridge.web.file_open_ready",
        "performance.bridge.web.intake_apply",
        "performance.bridge.web.intake_frame",
        "performance.bridge.web.pane_presentation",
        "performance.bridge.web.push_apply",
        "performance.bridge.web.projection_input_build",
        "performance.bridge.web.projection_store_apply",
        "performance.bridge.web.projection_total",
        "performance.bridge.web.review_content_demand",
        "performance.bridge.web.review_ready",
        "performance.bridge.web.review_metadata_apply",
        "performance.bridge.web.selection_commit",
        "performance.bridge.web.selected_content_dropped",
        "performance.bridge.web.selected_content_painted",
        "performance.bridge.web.selected_content_ready",
        "performance.bridge.web.rpc_send",
        "performance.bridge.web.telemetry_drop",
        "performance.bridge.web.viewer_activation",
        "performance.bridge.web.visible_demand_settled",
        "performance.bridge.web.worktree_file_intake_reject",
        "performance.bridge.markdown.render_queue",
        "performance.bridge.markdown.render",
        "performance.bridge.markdown.fallback",
        "performance.bridge.trees.projection_build",
        "performance.bridge.trees.prepare_input",
        "performance.bridge.trees.scroll_visible_demand",
        "performance.bridge.trees.click_to_row_highlight",
        "performance.bridge.trees.hover_to_render",
        "performance.bridge.trees.scroll_frame_gap",
        "performance.bridge.trees.anchor_restore",
        "performance.bridge.trees.scroll_to_path",
        "performance.bridge.trees.visible_ids_capture",
        "performance.bridge.trees.mode_switch",
        "performance.bridge.trees.search_filter",
        "performance.bridge.viewer.content_queue",
        "performance.bridge.viewer.content_cache",
        "performance.bridge.viewer.time_to_first_interaction",
        "performance.bridge.pierre.item_update",
        "performance.bridge.pierre.scroll_target",
        "performance.bridge.pierre.virtualized_range",
        "performance.bridge.shiki.highlight",
        "performance.bridge.worker.task",
    ]).union(BridgeRenderDispositionTelemetryContract.eventNames)

    static let allowedStringValuesByAttributeKey: [String: Set<String>] = [
        "agentstudio.bridge.activation.cause": [
            "context_switcher",
            "native_request",
            "review_file_corner",
        ],
        "agentstudio.bridge.activation.from_viewer": [
            "file",
            "review",
        ],
        "agentstudio.bridge.active_source.protocol": [
            "none",
            "review",
            "worktree-file",
        ],
        "agentstudio.bridge.active_viewer.mode": [
            "file",
            "review",
        ],
        "agentstudio.bridge.active_viewer.signal_rejection_reason": [
            "session_reset",
            "stale_generation",
            "stale_sequence",
        ],
        "agentstudio.bridge.anchor_restore.phase": [
            "capture",
            "direct_restore",
            "path_order_restore",
            "raf_restore",
            "scroll_to_path_reveal",
        ],
        "agentstudio.bridge.cache.result": [
            "cache_hit",
            "provider_load",
            "in_flight_coalesced",
            "rejected",
        ],
        "agentstudio.bridge.comparison.attempt.status": [
            "absent",
            "no_source",
            "pending",
            "selection_required",
            "settled",
            "unavailable",
        ],
        "agentstudio.bridge.comparison.package_match": [
            "matched",
            "snapshot_not_current",
            "package_absent",
            "package_id_mismatch",
            "review_generation_mismatch",
            "revision_mismatch",
        ],
        "agentstudio.bridge.comparison.pane_state": [
            "failed_initial",
            "failed_previous",
            "loading_initial",
            "loading_previous",
            "settled",
        ],
        "agentstudio.bridge.content.correlation_mode": [
            "summary",
            "traceparent",
        ],
        "agentstudio.bridge.content.role": [
            "base",
            "head",
            "diff",
            "file",
            "unknown",
        ],
        "agentstudio.bridge.content.interest": [
            "background",
            "selected",
            "unspecified",
            "visible",
            "nearby",
            "speculative",
        ],
        "agentstudio.bridge.demand.lane": [
            "active",
            "foreground",
            "idle",
            "nearby",
            "speculative",
            "visible",
        ],
        "agentstudio.bridge.demand.disposition": [
            "active-preloaded",
            "cache-hit",
            "cold-loaded",
            "idle-preloaded",
            "nearby-preloaded",
            "none",
            "published",
            "refreshed",
            "speculative-preloaded",
            "visible-preloaded",
        ],
        "agentstudio.bridge.drop_reason": [
            "contenthash_change",
            "generation_rotation",
            "revision_churn",
            "stale_after_fetch",
            "stale_before_fetch",
            "stale_before_publish",
        ],
        "agentstudio.bridge.file_size_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
            "unknown",
        ],
        "agentstudio.bridge.frame_jank.kind": [
            "dropped_frame",
            "long_task",
        ],
        "agentstudio.bridge.content.priority": [
            "background",
            "nearby",
            "prefetch",
            "selected",
            "speculative",
            "visible",
        ],
        "agentstudio.bridge.content_bytes_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
            "unknown",
        ],
        "agentstudio.bridge.diff_row_count_bucket": [
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.fixture_class": [
            "smoke",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.generation.relation": [
            "current",
            "stale",
            "unknown",
        ],
        "agentstudio.bridge.generation_relation": [
            "current",
            "stale",
            "unknown",
        ],
        "agentstudio.bridge.intake.frame_kind": [
            "review.invalidate",
            "review.metadataDelta",
            "review.metadataSnapshot",
            "review.metadataWindow",
            "review.reset",
            "unknown",
        ],
        "agentstudio.bridge.input.source": [
            "keyboard",
            "mouse",
            "programmatic",
        ],
        "agentstudio.bridge.package_build.reason": [
            "filesystem_refresh",
            "initial_intake",
            "intake_reannounce",
            "suppression_catch_up",
        ],
        "agentstudio.bridge.panel.operation": [
            "reset",
            "upsert",
        ],
        "agentstudio.bridge.presentation.disposition": [
            "applied",
            "idempotent_replay",
            "published",
            "rendered",
        ],
        "agentstudio.bridge.native_capacity.activity_rank": [
            "dormant",
            "foreground",
            "loaded_hidden",
            "unranked",
        ],
        "agentstudio.bridge.native_capacity.event": [
            "build_failed",
            "build_ready",
            "build_started",
            "coalesced",
            "consumer_cancelled",
            "consumer_joined",
            "draining",
            "entry_removed",
            "file_preparation_published",
            "file_window_appended",
            "invalidated",
            "lease_released",
            "logical_cancellation",
            "logical_timeout",
            "physically_returned",
            "queued",
            "slot_released",
            "stale_completion_dropped",
            "started",
            "tombstone_created",
        ],
        "agentstudio.bridge.native_capacity.operation_class": [
            "review_metadata",
            "selected_visible_content",
        ],
        "agentstudio.bridge.native_capacity.product_kind": [
            "file",
            "review",
        ],
        "agentstudio.bridge.phase": Set([
            "accepted",
            "active_viewer_mode_suppression_catch_up",
            "active_viewer_mode_signal_accepted",
            "active_viewer_mode_signal_rejected",
            "apply",
            "authorization",
            "content_register",
            "delta_build",
            "dispatch",
            "dropped",
            "encode",
            "error",
            "file_open_ready",
            "file_prepare_started",
            "file_prepare_terminal",
            "file_content_operation_started",
            "file_content_operation_terminal",
            "file_descriptor_wait_started",
            "file_descriptor_wait_terminal",
            "fetch",
            "frame_jank",
            "git_read_scheduler",
            "package_apply",
            "package_build",
            "pane_presentation_applied",
            "pane_presentation_enqueued",
            "pane_presentation_not_enqueued",
            "panel_chrome_applied",
            "panel_chrome_published",
            "render",
            "reservation_claim",
            "scheduled_capture",
            "send",
            "success",
            "terminal",
            "transport",
            "worktree_product_construction",
            "content_queue",
            "content_cache",
            "code_view_item_materialize",
            "comparison_pane_rendered",
            "comm_worker_session_snapshot",
            "highlight",
            "intake",
            "item_update",
            "markdown_decision",
            "markdown_queue",
            "markdown_render",
            "demand_queue_wait",
            "metadata_full_manifest_complete",
            "metadata_bootstrap_finished",
            "metadata_bootstrap_started",
            "metadata_open_to_first_window",
            "metadata_producer_cancelled",
            "metadata_producer_failed",
            "metadata_scheduler_job_execution",
            "metadata_scheduler_overflow_drop",
            "metadata_scheduler_stale_drop",
            "metadata_subscription_reset_enqueued",
            "metadata_enqueue_started",
            "metadata_enqueue_terminal",
            "content_operation_started",
            "content_operation_terminal",
            "annotation_invalidation_received",
            "annotation_invalidation_admitted",
            "annotation_notification_delivery_terminal",
            "annotation_paint_started",
            "annotation_paint_terminal",
            "content_transfer_started",
            "content_transfer_terminal",
            "descriptor_claim_started",
            "descriptor_claim_terminal",
            "main_thread_install_started",
            "metadata_delivery_started",
            "metadata_delivery_terminal",
            "native_annotation_work_started",
            "native_annotation_work_terminal",
            "main_thread_install_terminal",
            "projection_content_transfer_terminal",
            "projection_content_transfer_started",
            "projection_convergence_started",
            "projection_convergence_terminal",
            "projection_query_started",
            "projection_query_terminal",
            "projection_store_started",
            "projection_store_terminal",
            "projection_validation_started",
            "projection_validation_terminal",
            "refresh_commit_started",
            "refresh_commit_terminal",
            "refresh_reserved",
            "refresh_operation_terminal",
            "review_prepare_started",
            "review_prepare_terminal",
            "review_refresh_candidate_failed",
            "review_refresh_candidate_held",
            "review_refresh_candidate_ready",
            "review_refresh_candidate_superseded",
            "review_refresh_classified",
            "review_refresh_cleanup_terminal",
            "review_refresh_install_requested",
            "review_refresh_install_terminal",
            "review_refresh_receipt_failed",
            "review_refresh_source_cleanup_terminal",
            "render_operation_started",
            "render_operation_terminal",
            "paint_fulfillment_started",
            "paint_fulfillment_terminal",
            "panel_chrome_publish_started",
            "panel_chrome_publish_terminal",
            "worker_application_started",
            "worker_application_terminal",
            "mode_switch",
            "prepare_input",
            "projection_input_build",
            "projection_store_apply",
            "projection_total",
            "projection_build",
            "review_content_demand",
            "review_metadata_publication_completed",
            "review_metadata_publication_failed",
            "review_metadata_publication_started",
            "review_ready",
            "review_metadata_apply",
            "scroll_visible_demand",
            "click_to_row_highlight",
            "hover_to_render",
            "scroll_frame_gap",
            "anchor_restore",
            "scroll_to_path",
            "visible_ids_capture",
            "scroll_target",
            "search_filter",
            "selection_commit",
            "viewer_activation_requested",
            "selected_content_dropped",
            "selected_content_painted",
            "selected_content_ready",
            "time_to_first_interaction",
            "visible_demand_settled",
            "virtualized_range",
            "worktree_file_frame_apply",
            "worktree_file_projection",
            "worker_task",
        ]).union(BridgeAnnotationCatalogTelemetryContract.phaseValues)
            .union(BridgeRenderDispositionTelemetryContract.phaseValues),
        "agentstudio.bridge.plane": Set(
            BridgeTelemetryPlane.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.priority": Set(
            BridgeTelemetryPriority.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.rpc.method_class": [
            "other",
            "review",
            "telemetry",
        ],
        "agentstudio.bridge.item_count_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.item_update.kind": [
            "add",
            "hydrate",
            "replace",
        ],
        "agentstudio.bridge.language_class": [
            "config",
            "markdown",
            "other",
            "swift",
            "text",
            "typescript",
        ],
        "agentstudio.bridge.markdown.fallback_reason": [
            "binaryContent",
            "contentPending",
            "contentUnavailable",
            "diffPatchResource",
            "invalidResourceUrl",
            "largeContent",
            "missingSelectedItem",
            "noSelectedItem",
            "notMarkdown",
            "twoSidedDiff",
            "workerUnavailable",
        ],
        "agentstudio.bridge.projection.kind": [
            "all_files",
            "changed_files",
            "current_change_set",
            "custom",
            "docs_and_plans",
            "guided_review",
            "normal_review",
            "plans_and_specs",
            "source",
            "tests",
        ],
        "agentstudio.bridge.protocol": [
            "pane-presentation",
            "review",
            "worktree-file",
        ],
        "agentstudio.bridge.query_class": [
            "empty",
            "extension",
            "path",
            "symbol",
        ],
        "agentstudio.bridge.queue.depth_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.result": [
            "added",
            "cancelled",
            "claimed",
            "complete",
            "deferred",
            "dropped",
            "error",
            "failed",
            "failure",
            "fallback",
            "inactive",
            "production_failed",
            "queued",
            "skipped",
            "stale",
            "started",
            "success",
            "unchanged",
            "unavailable",
            "unsupported_content",
            "updated",
        ],
        "agentstudio.bridge.result_reason": [
            "admission_failed",
            "admission_rejected",
            "apply_now",
            "automatic",
            "aborted",
            "byte_budget_exceeded",
            "carrier_nonce_mismatch",
            "closed",
            "close",
            "commits",
            "concurrency_exceeded",
            "cancellation",
            "content_unavailable",
            "descriptor_missing",
            "descriptor_rejected",
            "duplicate_sequence",
            "frame_decode_failed",
            "frame_acknowledgement_rejected",
            "frame_delivery_rejected",
            "frame_too_large",
            "generation_mismatch",
            "host_port_message_invalid",
            "intake_error",
            "invalid_request_url",
            "load_failed",
            "load_threw",
            "lines",
            "event_construction",
            "file_source_unavailable",
            "files",
            "metadata_request_duplicate_object_member",
            "metadata_request_input_exceeds_ceiling",
            "metadata_request_invalid_json",
            "metadata_request_invalid_utf8",
            "metadata_request_member_count_exceeds_ceiling",
            "metadata_request_nesting_exceeds_ceiling",
            "metadata_carry_forward_verification",
            "missing_carrier_nonce",
            "deduplicated",
            "no_active_stream",
            "no_demand",
            "none",
            "not_retryable",
            "preview_only",
            "producer_queue_reset",
            "producer_rejected",
            "producer_retirement_failed",
            "producer_rejection",
            "producer_rejection_close_required",
            "producer_rejection_frame_identity_mismatch",
            "promotion_stale",
            "receipt_failed",
            "worker_replacement",
            "producer_rejection_frame_kind_mismatch",
            "producer_rejection_frame_lifecycle_mismatch",
            "producer_rejection_frame_too_large",
            "producer_rejection_lifecycle_closed",
            "producer_rejection_opening_frame_already_admitted",
            "producer_rejection_opening_frame_required",
            "producer_rejection_sequence_exhausted",
            "producer_rejection_terminal_already_admitted",
            "producer_rejection_unknown_lease",
            "receiver_rejected_frame",
            "response_delivery_rejected",
            "reset_enqueue_failure",
            "reset_required",
            "retryable",
            "review_event_construction",
            "review_source_unavailable",
            "review_subscription_missing",
            "sequence_gap",
            "session_enqueue_failure",
            "snapshot_descriptor_mismatch",
            "snapshot_materializer_rejected",
            "snapshot_package_parse_failed",
            "source_reset",
            "stale_completion",
            "stale_sequence",
            "stream_mismatch",
            "task_cancellation",
            "unknown",
            "unexpected",
        ],
        "agentstudio.bridge.review.refresh.install_trigger": [
            "apply_now",
            "automatic",
        ],
        "agentstudio.bridge.review.refresh.presentation_class": [
            "ordinary",
            "promoted",
        ],
        "agentstudio.bridge.review.refresh.promotion_reason": [
            "commits",
            "files",
            "lines",
            "none",
            "unknown",
        ],
        "agentstudio.bridge.selection.origin": [
            "context_switcher",
            "native_request",
            "review_file_corner",
        ],
        "agentstudio.bridge.scroll_target.kind": [
            "item",
            "line",
            "position",
            "range",
        ],
        "agentstudio.bridge.scroll.offset": [
            "nearest",
            "none",
            "top",
            "unknown",
        ],
        "agentstudio.bridge.scroll.reason": [
            "anchor_workaround",
            "append_reveal",
            "clicked_selection",
            "search_match",
            "selected_path_effect",
            "selection_sync",
        ],
        "agentstudio.bridge.slice": Set(
            BridgeTelemetrySlice.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.telemetry.drop_reason": Set(
            BridgeTelemetryDropReason.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.telemetry.event_name": allowedEventNames,
        "agentstudio.bridge.telemetry.first_rejected_event": allowedEventNames.union([
            unknownRejectedEventName
        ]),
        "agentstudio.bridge.telemetry.lane": Set(
            BridgeTelemetryPriority.allCases.map(\.rawValue)
        ).union(["unknown"]),
        "agentstudio.bridge.telemetry.result": [
            "dropped",
            "success",
            "unknown",
        ],
        "agentstudio.bridge.test.scenario": [
            "package_apply_content_fetch_v1"
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.expected_bootstrap.protocol": [
            "review",
            "worktree-file",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.bootstrap.protocol": [
            "review",
            "worktree-file",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_frame_kind": [
            "none",
            "worktree.reset",
            "worktree.snapshot",
            "worktree.treeWindow",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_reason": [
            "drop_frame_too_large",
            "drop_identity_mismatch",
            "drop_missing_push_nonce",
            "drop_nonce_mismatch",
            "drop_parse_failed",
            "frame_published",
            "handshake_received",
            "listener_installed",
            "none",
            "open_accepted",
            "replay_requested",
            "snapshot_resolved",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_receiver_reason": [
            "closed",
            "duplicate_sequence",
            "generation_mismatch",
            "none",
            "reset_required",
            "sequence_gap",
            "stale_sequence",
            "stream_mismatch",
        ],
        "agentstudio.bridge.transport": [
            "content",
            "intake",
            "local",
            "push",
            "rpc",
            "scheme",
            "swift",
            "worker",
        ],
        "agentstudio.bridge.tree_path_count_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.visible_row_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.viewer": [
            "all",
            "file",
            "review",
        ],
        "agentstudio.bridge.viewer.ttfi_variant": [
            "cold",
            "warm",
        ],
        "agentstudio.bridge.worker.lane": [
            "background",
            "file_view",
            "nearby",
            "none",
            "markdown",
            "pierre",
            "projection",
            "selected",
            "speculative",
            "visible",
        ],
        "agentstudio.bridge.worker.semantic_class": [
            "demand",
            "lifecycle_control",
            "settlement",
            "urgent_action",
        ],
        "agentstudio.bridge.worker.file_mode_dispatch": [
            "dropped_detached",
            "none",
            "posted",
            "queued_not_ready",
        ],
        "agentstudio.bridge.worker.file_select_dispatch": [
            "dropped_detached",
            "none",
            "posted",
            "queued_not_ready",
        ],
        "agentstudio.bridge.worker.review_select_dispatch": [
            "dropped_detached",
            "none",
            "posted",
            "queued_not_ready",
        ],
        "agentstudio.bridge.worker.session_state": [
            "awaiting_bootstrap",
            "bootstrapping",
            "disposed",
            "failed",
            "ready",
            "replacement_requested",
        ],
        "agentstudio.bridge.worker.replacement_reason": [
            "bootstrap_timeout",
            "explicit_dispose",
            "message_error",
            "none",
            "runtime_recovery",
            "session_in_use",
            "session_suspect",
            "worker_error",
        ],
        "agentstudio.bridge.worker.replacement_source": [
            "admission_reply_exhausted",
            "none",
            "render_disposition_overload",
            "render_disposition_probe_exhausted",
            "result_acknowledgement_exhausted",
            "result_deadline_exhausted",
            "review_installed_receipt_failed",
        ],
        "agentstudio.bridge.worker.task_kind": [
            "content_preparation",
            "highlight",
            "markdown_render",
            "message_handler",
            "pool_init",
            "product_control",
            "projection",
            "store_action",
        ],
        "agentstudio.bridge.worker.action": [
            "applyContentReady",
            "applyContentTerminalAvailability",
            "applyFileViewSourceMutationFact",
            "applyFileViewSourceUpdateFact",
            "applyReviewInvalidationFact",
            "applyReviewRowMutationFact",
            "applyReviewSourceUpdateFact",
            "applySelectedFact",
            "applySelectedSourceChurnFact",
            "applyViewportFact",
        ],
        "agentstudio.bridge.worker.command": [
            "activeViewerModeUpdate",
            "annotationCommand",
            "annotationOutputInspect",
            "annotationProjectionRetry",
            "fileDisplayResync",
            "fileQueryUpdate",
            "fileRefreshRetry",
            "fileSourceDiscovery",
            "hover",
            "markFileViewed",
            "metadataInterestUpdate",
            "mode",
            "renderDisposition",
            "reviewComparisonTargetsQuery",
            "reviewComparisonTargetsQueryCancel",
            "reviewComparisonUpdate",
            "reviewIntakeReady",
            "reviewInvalidate",
            "reviewProjectionUpdate",
            "reviewPublicationInstallAdmit",
            "reviewPublicationInstalled",
            "select",
            "viewport",
        ],
        "agentstudio.bridge.worker.payload_class": [
            "inline",
            "source_reset",
        ],
        "agentstudio.bridge.worker.work_kind": [
            "file_view_content_ready",
            "review_content_ready",
            "review_source_reset",
        ],
    ].merging(BridgeRenderDispositionTelemetryContract.outcomeValues) { existingValues, renderValues in
        existingValues.union(renderValues)
    }

}
