import AgentStudioCore

extension WorkspaceActionCommand {
    var performanceTraceName: String {
        switch self {
        case .selectTab:
            return "selectTab"
        case .closeTab:
            return "closeTab"
        case .breakUpTab:
            return "breakUpTab"
        case .renameTab:
            return "renameTab"
        case .closePane:
            return "closePane"
        case .extractPaneToTab:
            return "extractPaneToTab"
        case .insertPaneRequest:
            return "insertPaneRequest"
        case .resizePane:
            return "resizePane"
        case .resizeVisiblePanePair:
            return "resizeVisiblePanePair"
        case .equalizePanes:
            return "equalizePanes"
        case .moveTab:
            return "moveTab"
        case .reorderTab:
            return "reorderTab"
        case .resizePaneByDelta:
            return "resizePaneByDelta"
        case .mergeTab:
            return "mergeTab"
        case .movePaneAcrossTabs:
            return "movePaneAcrossTabs"
        case .createArrangement:
            return "createArrangement"
        case .removeArrangement:
            return "removeArrangement"
        case .switchArrangement:
            return "switchArrangement"
        case .renameArrangement:
            return "renameArrangement"
        case .openWorktree:
            return "openWorktree"
        case .openNewTerminalInTab:
            return "openNewTerminalInTab"
        case .openWorktreeInPane:
            return "openWorktreeInPane"
        case .openFloatingTerminal:
            return "openFloatingTerminal"
        case .removeRepo:
            return "removeRepo"
        case .setPanePinned:
            return "setPanePinned"
        case .setRepoPinned:
            return "setRepoPinned"
        case .minimizePane:
            return "minimizePane"
        case .expandPane:
            return "expandPane"
        case .backgroundPane:
            return "backgroundPane"
        case .reactivatePane:
            return "reactivatePane"
        case .purgeOrphanedPane:
            return "purgeOrphanedPane"
        case .enterDrawer:
            return "enterDrawer"
        case .focusDrawerPaneUp:
            return "focusDrawerPaneUp"
        case .focusDrawerPaneLeft:
            return "focusDrawerPaneLeft"
        case .focusDrawerPaneDown:
            return "focusDrawerPaneDown"
        case .focusDrawerPaneRight:
            return "focusDrawerPaneRight"
        case .detachDrawerPane:
            return "detachDrawerPane"
        case .addDrawerPane:
            return "addDrawerPane"
        case .addWebviewDrawerPane:
            return "addWebviewDrawerPane"
        case .addDrawerChildInBackground:
            return "addDrawerChildInBackground"
        case .removeDrawerPane:
            return "removeDrawerPane"
        case .toggleDrawer:
            return "toggleDrawer"
        case .setActiveDrawerPane:
            return "setActiveDrawerPane"
        case .resizeDrawerPane:
            return "resizeDrawerPane"
        case .resizeDrawerVisiblePanePair:
            return "resizeDrawerVisiblePanePair"
        case .equalizeDrawerPanes:
            return "equalizeDrawerPanes"
        case .minimizeDrawerPane:
            return "minimizeDrawerPane"
        case .expandDrawerPane:
            return "expandDrawerPane"
        case .insertDrawerPane:
            return "insertDrawerPane"
        case .setZoomSplitRatio:
            return "setZoomSplitRatio"
        case .setDrawerNormalHeightRatio:
            return "setDrawerNormalHeightRatio"
        case .setDrawerZoomSide:
            return "setDrawerZoomSide"
        case .moveDrawerPane:
            return "moveDrawerPane"
        case .expireUndoEntry:
            return "expireUndoEntry"
        case .repair:
            return "repair"
        }
    }
}
