// The closed glyph set the recreation kit draws. Shapes approximate the SF
// Symbols visible in web/src/assets/captures/; they are drawn, not copied.
export const kitIconNames = [
  "search",
  "sort",
  "repository",
  "columns",
  "trash",
  "pane",
  "terminal",
  "branch",
  "worktree",
  "stack",
  "bell",
  "folder-plus",
  "layout-grid",
  "arrangement",
  "chevron-left",
  "chevron-right",
  "chevron-down",
  "plus",
  "drawer",
  "pencil",
  "pull-request",
  "code",
  "copy",
  "zoom",
  "folder",
  "file",
  "file-typescript",
  "file-markdown",
  "gear",
  "files",
  "review",
  "sliders",
  "close-circle",
  "clock",
  "return",
  "arrow-right",
  "check",
] as const;

export type KitIconName = (typeof kitIconNames)[number];
